# DigitalOcean App Platform Configuration
# Place this file at the root of your repository
# DigitalOcean will automatically detect and use it

name: panastream
region: sfo3

services:
  - name: api
    github:
      repo: your-org/pana-stream  # UPDATE: Your GitHub username/org and repo name
      branch: main
      deploy_on_push: true
    
    # Server-only deployment - build from server directory
    source_dir: /server
    build_command: npm install
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # HTTP configuration
    http_port: 3001
    routes:
      - path: /
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables - Set these in DigitalOcean dashboard
    envs:
      # API Security (REQUIRED - Set as SECRET)
      - key: PANASTREAM_API_TOKEN
        scope: RUN_TIME
        type: SECRET
        value: ""  # Generate with: node generate-token.js
        
      # Server Configuration
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: PORT
        scope: RUN_TIME
        value: "3001"
      
      # AWS Configuration (REQUIRED - Set as SECRET)
      - key: AWS_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
        value: ""
      - key: AWS_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
        value: ""
      - key: AWS_REGION
        scope: RUN_TIME
        value: "us-east-1"
      
      # S3 Configuration (REQUIRED)
      - key: S3_BUCKET_NAME
        scope: RUN_TIME
        type: SECRET
        value: ""
      - key: S3_UPLOAD_FOLDER
        scope: RUN_TIME
        value: "uploads"
      - key: S3_PROCESSED_FOLDER
        scope: RUN_TIME
        value: "processed"
      
      # CloudFront Configuration (REQUIRED)
      - key: CLOUDFRONT_DOMAIN
        scope: RUN_TIME
        value: "vod.panastream.pixaclara.io"  # Update with your domain
      
      # MediaConvert Configuration (REQUIRED - Set as SECRET)
      - key: MEDIACONVERT_ENDPOINT
        scope: RUN_TIME
        value: "https://mediaconvert.us-east-1.amazonaws.com"
      - key: MEDIACONVERT_ROLE_ARN
        scope: RUN_TIME
        type: SECRET
        value: ""
      
      # Database
      - key: DATABASE_PATH
        scope: RUN_TIME
        value: "./database.sqlite"
      
      # CORS Configuration
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: "https://fabricatedcrime.com"
      - key: APP_URL
        scope: RUN_TIME
        value: "https://panastream.fabricatedcrime.com"

# Domain configuration
domains:
  - domain: panastream.fabricatedcrime.com
    type: PRIMARY
